### ISSUE TITLE
Homepage not displaying all books

### ISSUE THREAD

**Issue by rgaudin** [kiwix/libkiwix#658] opened 2021-12-13 12:16 UTC
I have a library with 104 books. Kiwix serve doesn't print any error and the welcome page properly says that I have 104 books.

<img width="555" alt="Screen Shot 2021-12-13 at 12 10 15" src="https://user-images.githubusercontent.com/57929/145809873-b11cc0e4-bfe3-4a0e-8c00-6855c71a6d35.png">

The problem is that, without any filter enabled, that homepage only displays `13` or `15` books. Yes, that number changes upon refreshes…

There is no error in the console.

I suppose it's one of several ZIM files that are problematic because many of those ZIMs are dev/test files but without any error/warning, it's hard to debug. Is there a way to find that out instead of trying them all individually (which is not guaranteed to trigger anything) ?

**Comment by kelson42** [comment] 2021-12-13 12:50
New tiles should load id you scroll down. I guess it does not. What is screen resolution?

**Comment by rgaudin** [comment] 2021-12-13 12:52
Indeed, it does not. Resolution is 3072 x 1920 Retina

**Comment by kelson42** [comment] 2021-12-13 12:53
@MananJethwani Any idea?

**Comment by kelson42** [comment] 2021-12-13 13:04
Actually this pretty exactly the same bug #603 reported a few months by @jmontleon

**Comment by kelson42** [comment] 2021-12-21 17:25
@rgaudin I have tried to reproduce the problem but without success. I can not go that high in resolution, but somehow suspect this is linked to the pixel depth.

**Comment by kelson42** [comment] 2022-01-03 20:33
@rgaudin Is this ticket a duplicate of #607? Does #667 fixes this ticket as well?

**Comment by rgaudin** [comment] 2022-01-03 21:08
#607 fixes this ; sorry I used 603 by mistake

**Closed** 2022-01-03 21:09 UTC
Labels: bug, kiwix-serve
