### ISSUE TITLE
Expose counter on meta endpoint

### ISSUE THREAD

**Issue by rgaudin** [kiwix/libkiwix#616] opened 2021-09-28 15:08 UTC
Currently, we can't access `Counter` metadata via kiwix-serve. I've set this as *bug* because it's a regression but might have been removed on purpose.

I know that @kelson42 also relies on this.

https://github.com/kiwix/libkiwix/blob/3b942bb7458af7daae00505b4a660a47eb33628f/src/server/internalServer.cpp#L404-L427

Side questions:
- Why the change in case? Metadata are title case and having to switch feels unnatural.
- Why not offering all metadata using this endpoint? I see that all of the supported ones have a dedicated getter here. Maybe we should provide a generic one as well, to be used for others?

**Comment by maneeshpm** [comment] 2021-09-28 18:31
@rgaudin I agree, title case would have been better here, the metadata are still stored in Title case inside our archive. Having a lowercase middle process might introduce confusion.

We require dedicated getters for several metadata that might require some preprocessing, like `getArchiveTitle()`, `getMetaTags()`, `getArchiveFavicon()` etc. But for the generic ones like `Name`, `Language` etc the dedicated getters are mere helpers for the generic `getMetadata(archive, metadata)` function(see [archiveTools.cpp](https://github.com/kiwix/libkiwix/blob/master/src/tools/archiveTools.cpp). We can expose the generic function, given the metadata can be extracted as a string. 

Apart from this, we do have a dedicated function for getting counter metadata as well.

**Comment by mgautierfr** [comment] 2021-09-29 09:51
> Currently, we can't access Counter metadata via kiwix-serve. I've set this as bug because it's a regression but might have been removed on purpose.

While I agree we should be able to access the `M/Counter` metadata (and all others), this feature was never there.
I've added the `/meta` endpoint mainly because the opds stream was needing to access the favicon of the zim file (to not include the icon data in the stream).
I've also add some other metadata (not used at the time) in the same change and simply "forgot" `M/Counter`.

**Comment by rgaudin** [comment] 2021-09-29 09:52
I meant with namespaced ZIM, we could just use the full path like `M/Counter`

**Comment by mgautierfr** [comment] 2021-09-29 10:04
Indeed. My bad.

**Comment by kelson42** [comment] 2021-11-21 16:14
Kind of duplicate of #631 now.

**Closed** 2022-01-05 14:31 UTC
Labels: bug, kiwix-serve
