### ISSUE TITLE
Snippets for suggestions should return highlighted title, not content.

### ISSUE THREAD

**Issue by mgautierfr** [kiwix/libkiwix#82] opened 2017-08-18 02:01 UTC
The suggestions method of the searcher is searching in the title, not the content.
And if we are searching for suggestion, we will display the title to the user, not the content.

So in this case, snippets should return highlighted title.

**Comment by maneeshpm** [comment] 2021-04-16 21:20
I was able to get the snippet by adding a new method `search_iterator::get_titleSnippet` to libzim. Seems like replacing the title string with snippet string does not guarantee rendering. 
![Screenshot from 2021-04-17 02-44-08](https://user-images.githubusercontent.com/45821104/115084831-0d437e00-9f27-11eb-882a-80996e29e1fa.png)
@kelson42 Any idea how to get the HTML rendering sorted?

**Comment by kelson42** [comment] 2021-04-17 04:59
@maneeshpm Great! Regarding the rendering, we had recently afew ticket fixed regarding this. @maneeshpm @veloman-yunkan an idea?

**Comment by maneeshpm** [comment] 2021-04-17 14:42
@kelson42 I agree, not all systems can render HTML. I think we can just push the snippet [here](https://github.com/kiwix/kiwix-lib/blob/11db5dec4ea0d039b54ec593d2e9ad51ba33aff2/src/reader.cpp#L510) and handle the added string accordingly in `handle_suggest`. This way we can implement it in kiwix-serve, and leave it available(but optional) to be used in other clients as well.

**Comment by kelson42** [comment] 2021-04-17 14:44
@maneeshpm Sounds good to me. For my information the `<b>` tags are added by Xapian or by the Libzim?

**Comment by maneeshpm** [comment] 2021-04-17 15:19
We are generating the snippet by a `Xapian::MSet::get_snippet` method. It adds the tags.

**Comment by veloman-yunkan** [comment] 2021-04-18 12:29
> @maneeshpm Great! Regarding the rendering, we had recently a few tickets fixed regarding this. @maneeshpm @veloman-yunkan an idea?
> 
> There is a bit as well an architectural question... because not all tje client might be able to render HTML. This keyword highlighting shoukd probably be optional.

It shouldn't be hard to handle it on both sides (front and back ends) of kiwix-serve. I concur that the keyword highlighting must be optional (and off by default).

**Comment by mgautierfr** [comment] 2021-04-19 08:51
The snippet generation is known to be slow, mainly because we need to load the content to be able to locate interesting part of the content and highlight words.
This is probably a issue only for full textsearch as we load the content from the zim file for all articles in the search page result.
For suggestion it is probably not so important as we load only the title from the xapian database or from the dirent. (no decompression of article). But we must check that.
Also, `Xapian::MSet::get_snippet` may return only a part of the content (title). We must be sure that it only add highlight and not select a subset of the title.

And I agree to make the highlighting optional.

**Comment by maneeshpm** [comment] 2021-04-19 11:08
@mgautierfr Yes, the fulltext snippets have that problem. I can confirm that issue is not there in title snippets, since we retrieve the value directly from Xapian. We can request snippets with a max length such that we get the entire title and avoid only getting its subset. 

As you and @veloman-yunkan suggested, how shall we make it optional in kiwix serve? Where is it appropriate to add a switch?

**Comment by kelson42** [comment] 2021-04-19 14:25
@maneeshpm It should not be optional in Kiwix Serve (even it might be considered to keep the formating less string in the suggestion API for third party usages). It should be optional in libzim and libkiwix ABI.

**Comment by veloman-yunkan** [comment] 2021-04-19 15:17
> @maneeshpm It should not be optional in Kiwix Serve (even it might be considered to keep the formating less string in the suggestion API for third party usages). It should be optional in libzim and libkiwix ABI.

@kelson42 I think it should be an an option of the kiwix-serve suggestion API (or the response of the `/suggest` endpoint should contain both plain-text and HTML snippet versions).

**Comment by maneeshpm** [comment] 2021-04-19 15:29
@veloman-yunkan The `label` parameter in the response json sounds like a good candidate for inserting snippets. I wonder if this would break any project that depends on this API. If that's the case, we can add a new parameter.

**Comment by kelson42** [comment] 2021-04-19 19:32
@maneeshpm This sounds good indeed.

**Comment by kelson42** [comment] 2021-05-01 18:20
@maneeshpm Would you be able to amke a PR before https://github.com/openzim/libzim/issues/542 is merged? Might take a bit and would be sad to be blocked because of latency in the review process.

**Comment by maneeshpm** [comment] 2021-05-01 18:23
@kelson42 Sure I can do that! it is a good idea 👍

**Comment by mgautierfr** [comment] 2021-05-04 14:04
I wonder if we should make highlighting optional after all. The "snippet" will be the full title with queried term highlighted, if we don't have highlight, this is simply the title and it is easy to simple ask for it.

If we have this optional, it should be on kiwix-serve api to allow different kind of usage.

**Comment by kelson42** [comment] 2021-05-04 15:33
@mgautierfr I don't want this customizable for the end user in kiwix-serve. If someone wants this I would recommend to open a new ticket. The json provides both (with highlight and without) and this is the most important.

**Comment by kelson42** [comment] 2021-05-07 06:14
@maneeshpm Any news for this ticket?

**Comment by maneeshpm** [comment] 2021-05-07 06:51
@kelson42 Will open a PR by the weekend. I have my last end sem exam tomorrow 😅

**Closed** 2021-05-26 09:04 UTC
Labels: enhancement, search
