### ISSUE TITLE
Kiwix for iOS v1.15.1 does not open WikiHow articles

### ISSUE THREAD

**Issue by Popolechien** [kiwix/libkiwix#652] opened 2021-11-30 11:45 UTC
From a user running on iOS and using wikihow_en_maxi_2021-10.zim
Device is iphone 13 pro with ios 15.1.1 (latest version). 

Articles look blanked
![attachment](https://user-images.githubusercontent.com/21675885/144041451-cdc01af9-0e0f-4d84-80b7-c2e5ae09bc4e.png)

Search works, but then every entry opened returns the blank screen.
![attachment-1](https://user-images.githubusercontent.com/21675885/144041517-56ebcd5a-df86-4722-ba41-52f1d8aa75b0.png)

the user tested and this issue is not present on macOS. Darkmode / lightmode made no difference.
Reinstalling the app and rebooting does not solve it.
Wikipedia, both the english and swedish version (both maxi), works perfectly.

**Comment by kelson42** [comment] 2021-12-12 10:41
Same newly created http://download.kiwix.org/zim/stack_exchange/beer.stackexchange.com_en_all_2020-11.zim, I have the same symptom. Tends to believe this is a problem related to namespace than encoding.

**Comment by rgaudin** [comment] 2021-12-13 07:47
Agrees

**Comment by mgautierfr** [comment] 2021-12-21 15:58
Without further information I cannot really help you.
The master version of libkiwix works with both kiwix-serve and kiwix-desktop. I can open the beer.stackexchange pointed by @kelson42 correctly.
It seems that if there is something wrong, it is either specific to ios compilation or how you use libkiwix.

The following code works on my side.

```cpp
#include <kiwix/reader.h>

int main() {
	kiwix::Reader reader("beer.stackexchange.com_en_all_2020-11.zim");
	auto mainEntry = reader.getMainPage();
	std::cout << "Found main entry. Path : " << mainEntry.getPath() << std::endl;
	auto entry = reader.getEntryFromPath("A/question/605.html");
	std::cout << "Found entry. Path : " << entry.getPath() << std::endl;
	return 0;
}
```

(Compiled with `g++ open_beer_stackexchange.cpp -o open_beer -I $WDIR/BUILD_native_dyn/INSTALL/include/ -L $WDIR/BUILD_native_dyn/INSTALL/lib64/ -lkiwix -lzim -licui18n -licuuc -lpugixml`)

**Comment by kelson42** [comment] 2021-12-21 16:59
@mgautierfr I think you have tested with an old file (not without namespace). Probably because my link in the previous comment was wrong. Would you be able please to confirm the same test with https://mirror.download.kiwix.org/zim/stack_exchange/beer_stackexchange_com_2021-12.zim workd (but without `A/` in the URL)?

**Comment by mgautierfr** [comment] 2021-12-22 08:19
This work also with a recent zim file.
Here a updated version of the cpp test program, I've also added search.

```cpp
#include <kiwix/reader.h>
#include <kiwix/searcher.h>

int main() {
	kiwix::Reader reader("beer_stackexchange_com_2021-12.zim");
	auto mainEntry = reader.getMainPage();
	std::cout << "Found main entry. Path : " << mainEntry.getPath() << std::endl;
	std::string path = "questions/22/do-different-beer-glass-shapes-really-make-a-difference-in-taste";
	auto entry = reader.getEntryFromPath(path);
	std::cout << "Found entry. Path : " << entry.getPath() << std::endl;

	// This work also with the namespace
	std::string path1 = "C/questions/22/do-different-beer-glass-shapes-really-make-a-difference-in-taste";
	auto entry1 = reader.getEntryFromPath(path1);
	std::cout << "Found entry. Path1 : " << entry1.getPath() << std::endl;

	// And even a wrong namespace thank to compatibility layer introduced to handle old bookmarks
	std::string path2 = "A/questions/22/do-different-beer-glass-shapes-really-make-a-difference-in-taste";
	auto entry2 = reader.getEntryFromPath(path2);
	std::cout << "Found entry. Path2 : " << entry2.getPath() << std::endl;

	// Lets do search
	kiwix::Searcher searcher;
	searcher.add_reader(&reader);
	searcher.search("glass", 0, 10);
	auto result = searcher.getNextResult();
	while (result) {
		std::cout << " - We have a search result : " << result->get_url() << std::endl;
		auto entry = reader.getEntryFromPath(result->get_url());
		std::cout << "   And a entry found : " << entry.getPath() << std::endl;
		result = searcher.getNextResult();
	}
	return 0;
}
```

Of course the path format of the entries has changed, but it is what is in the zim file.

**Comment by kelson42** [comment] 2021-12-22 08:29
@automactic Would you be able please to check this exact very same calls with Swift and dev libkiwix11? And tell us if it behaves differently?

**Comment by kelson42** [comment] 2022-01-03 08:47
@automactic Any news on this? Without quick progresses, I will have to move it to on of the next release.

**Comment by kelson42** [comment] 2022-02-03 14:27
@automactic Without feedback on your side, I plan to close this ticket in the next weeks.

**Closed** 2022-02-09 06:01 UTC
Labels: bug

**Comment by MohitMaliFtechiz** [comment] 2022-09-27 13:06
hi @mgautierfr ,

This issue is still exist on android , I confirmed this is working with older version 9.4.1. Its showing wrong url on MainPage ```https://kiwix.app/``` expected ```https://kiwix.app/C/questions```

**Comment by mgautierfr** [comment] 2022-09-27 13:32
I'm not sure what is wrong from your description.
Did you expect android application to show `https://kiwix.app/C/questions` and `https://kiwix.app/` is displayed instead ?

**Comment by MohitMaliFtechiz** [comment] 2022-09-28 07:44
hi @mgautierfr ,

I have open separate ticket for problem. https://github.com/kiwix/libkiwix/issues/824
