### ISSUE TITLE
Search drop-down flows off bottom of screen

### ISSUE THREAD

**Issue by holta** [kiwix/libkiwix#809] opened 2022-08-17 19:02 UTC
Students cannot easily find the `Containing 'Haïti'...` Full-Text Search option at the bottom of the search drop-down here:

![image](https://user-images.githubusercontent.com/2458907/185221593-707b9b3d-6abf-4a52-88c2-8a24e2fa78b5.png)

FYI this is using kiwix-tools 3.3.0 on the latest Raspberry Pi OS on Raspberry Pi 400 with 36GB https://download.kiwix.org/zim/wikipedia/wikipedia_fr_all_maxi_2022-08.zim on https://internet-in-a-box.org :

```
root@box:~# /opt/iiab/kiwix/bin/kiwix-serve --version
kiwix-tools 3.3.0

libkiwix 11.0.0
+ libzim 7.2.2
+ libxapian 1.4.18
+ libcurl 7.67.0
+ libmicrohttpd 0.9.72
+ libz 1.2.12
+ libicu 58.2.0
+ libpugixml 0.12.0

libzim 7.2.2
+ libzstd 1.5.2
+ liblzma 5.2.4
+ libxapian 1.4.18
+ libicu 58.2.0
```

When the search query is 'Paris' (instead of 'Haïti') the drop-down requires you to scroll downwards for almost 100 pages!

_Is this user interface the new intended behavior?_

Tangentially related issues:

- kiwix/kiwix-tools#513
- #769

**Comment by kelson42** [comment] 2022-08-17 19:20
This is really weird that:
* the suggestion list is not under the search box
* that it is so long

**Comment by kelson42** [comment] 2022-08-17 19:24
@holta I can not reproduce the problem with https://library.kiwix.org/wikipedia_fr_all_maxi_2022-08/A/Port-au-Prince_(navire). Which seems to be the same content and the same version of kiwix-serve. Do you?

**Comment by holta** [comment] 2022-08-17 19:24
> the suggestion list is not under the search box

Ignore that (it resulted from changing the browser's font size right before I took a screenshot!)

> that it is so long

Long might be good!  But 100 pages of auto-suggested articles about 'Paris' is a bit too much ;-)

**Comment by holta** [comment] 2022-08-17 20:15
1) FYI I upgraded the Raspberry Pi from kiwix-tools 3.3.0 to 3.3.0-1 and the problem appears to have gone away (for now?)

2) What's very mysterious is that I then revert back to 3.3.0 and can no longer reproduce the problem :/

This appears to be an episodic bug (when it occurs, it occurs every single time &mdash; but I do not know the cause!)

PS kiwix-tools' changelog https://github.com/kiwix/kiwix-tools/blob/master/Changelog makes no mention of any differences between 3.3.0 and 3.3.0-1 &mdash; though it's evident there are differences when you run: _(below is 3.3.0-1 even though confusingly it does not say so)_

```
root@box:~# /opt/iiab/kiwix/bin/kiwix-serve --version
kiwix-tools 3.3.0

libkiwix 11.0.0
+ libzim 8.0.0
+ libxapian 1.4.18
+ libcurl 7.67.0
+ libmicrohttpd 0.9.72
+ libz 1.2.12
+ libicu 58.2.0
+ libpugixml 0.12.0

libzim 8.0.0
+ libzstd 1.5.2
+ liblzma 5.2.4
+ libxapian 1.4.18
+ libicu 58.2.0
```

**Comment by kelson42** [comment] 2022-08-18 05:03
Strange, only libzim has changed beetween two builds. My best guess. There is somehow a CSS cache problem, and using the new build has forced to refresh the cache. Closing the ticket for the moment. Please reopen if it appears again.

**Closed** 2022-08-18 05:03 UTC
Labels: bug, kiwix-serve, search
