### ISSUE TITLE
Taskbar broken by a copyright notice

### ISSUE THREAD

**Issue by veloman-yunkan** [kiwix/libkiwix#653] opened 2021-12-12 13:33 UTC
The ZIM file [ted_en_playlist-5-questions-about-climate-change_2021-01.zim](http://download.kiwix.org/zim/ted/ted_en_playlist-5-questions-about-climate-change_2021-01.zim) contains a simple copyright notice (http://localhost:8080/ted_en_playlist-5-questions-about-climate-change_2021-01/A/assets/ogvjs/COPYING) that breaks the taskbar of the kiwix-serve frontend:

![broken_taskbar](https://user-images.githubusercontent.com/11933502/145714017-a4deb15a-bb37-4c0e-9ad9-c90abfa6610d.png)

The problem is that the HTML for that page is generated without the `<head></head>` section (as well as without the `<!DOCTYPE html>` preamble).

**Comment by kelson42** [comment] 2021-12-12 13:54
The problem is that this is text content with wrong mime-type. This was a bug at the scraper level which has been fixed... and this file has been removed anyway from the latest Version of this ZIM file that I made a few days ago. See https://github.com/openzim/ted/pull/124. I don't think there is anything to fix at libkiwix level.

**Comment by veloman-yunkan** [comment] 2021-12-12 15:41
@kelson42 Wouldn't it be better if libkiwix isn't that easily confused by items with wrong mime-type?

**Comment by kelson42** [comment] 2021-12-12 15:45
@veloman-yunkan Afaik this item has a text/html mime-type. The kiwix-serve is fooled by this, and this seems legit to me. I don't really what could be done to avoid that. Do you have a concrete improvment in mind?

**Comment by kelson42** [comment] 2021-12-12 15:51
Maybe an other reason to push #394?

**Comment by kelson42** [comment] 2021-12-16 06:14
@veloman-yunkan Closing the ticket as I don’t think we can do anything better in this ticket. Please reopen if you have a pragmatic improvement proposal.

**Closed by kelson42** 2021-12-16 06:14 UTC
Labels: question
