### ISSUE TITLE
Kiwix Server – Multiple hits, different contents scope, identical descriptions

### ISSUE THREAD

**Issue by srousset** [kiwix/libkiwix#726] opened 2022-03-14 16:09 UTC
Hello,

Seems to me that Kiwix Server doesn't make it easy to differentiate between variants of the same basic contents. It would be good to make it clear for the average user. An example is best to explain the issue (which isn't limited to that single example)…

In Kiwix Server, let's say that you select language = French (français), category = Wikipedia, and you leave the Search field empty. This will give you 39 books, the first three of which are identical tiles (same logo, same title, same short description, etc.) except for the file size. 
<img width="822" alt="Capture d’écran 2022-03-13 à 17 22 50" src="https://user-images.githubusercontent.com/20866309/158213346-b75b7c6d-44fe-430d-9b4b-79c92dfc7841.png">

OK, I can imagine that there's one variant without images, one with images, and, er…, another variant of some kind. In my view as a mere mortal, it would be helpful to show what's different, maybe by displaying the relevant attribute, or by adding it as plain text underneath the short description.

Thanks.

Best regards, Stéphane

**Comment by mgautierfr** [comment] 2022-03-16 10:52
I agree. We should add some information about the variants. This chould be "easily" fixed by displaying the different tags `_image`/`_video`/...

**Comment by kelson42** [comment] 2022-03-17 01:22
This is pretty much a duplicate of #421

**Closed** 2022-03-17 01:26 UTC
Labels: duplicate, enhancement, good first issue, kiwix-serve
