### ISSUE TITLE
Fallback server-side generated landing page and search for browsers without JavaScript

### ISSUE THREAD

**Issue by ge0rg** [kiwix/libkiwix#835] opened 2022-10-17 07:41 UTC
The "Welcome to Kiwix Server" landing page and wiki search on the `/` URL requires JavaScript to query the API for a list of matching books and to render the results.

While I appreciate the individual books popping up in a shiny animation, the result list is always empty on devices that do not support JavaScript, like older ebook readers which are a relevant target for offline reading of ZIMs.

This is also a regression in comparison to 2.1.0.

Actual result:
![image](https://user-images.githubusercontent.com/165635/196117291-e6e77a24-56cd-4726-b7c2-e3fc4f285330.png)

Anticipated result:
![image](https://user-images.githubusercontent.com/165635/196117416-2994b6d3-6ca3-421d-a183-73f8c6a91267.png)

**Comment by kelson42** [comment] 2022-11-02 18:36
Duplicate of #615

**Closed by kelson42** 2022-11-02 18:36 UTC
