### ISSUE TITLE
kiwix::NoEntry is raised when getting random page url

### ISSUE THREAD

**Issue by KingNexu** [kiwix/libkiwix#643] opened 2021-12-04 12:00 UTC
> [Kiwix for iOS v1.15.1]
> [iPhone XS]

App Crashes When the Random button is Pressed. **(No Library Open)**
App Crashes After a Few Button presses. **(Library is Open)**

Library ID: **44371d60**

 
https://user-images.githubusercontent.com/68326859/144708751-11608f1f-e98f-4e03-aaec-682cbb3c0682.MP4

**Comment by automactic** [comment] 2021-12-07 03:42
More context: it seems like this is more likely to happen on a zim file with small amount of articles. For example, try one of the zim files with mostly videos

**Comment by kelson42** [comment] 2021-12-07 03:44
@veloman-yunkan Is that a legit behaviour to get this noentry exception here?

**Comment by veloman-yunkan** [comment] 2021-12-07 07:41
> @veloman-yunkan Is that a legit behaviour to get this noentry exception here?

@kelson42 Yes, it is. `Archive::getRandomEntry()` performs at most 42 attempts - if it doesn't get an item with MIME type of `test/html` then it fails with an exception.

**Comment by kelson42** [comment] 2021-12-07 07:52
@mgautierfr @veloman-yunkan I guess this scenario mostly happens in the pre-libzim7 ZIM files as we can have for many reasons non-html content in the `A` namespace. But, with post-libzim7, because we have only "front articles" in Xapian title index, this scenario should not occur in a normal case. Right?

**Comment by veloman-yunkan** [comment] 2021-12-07 08:03
> I guess this scenario mostly happens in the pre-libzim7 ZIM files as we can have for many reasons non-html content in the `A` namespace. But, with post-libzim7, because we have only "front articles" in Xapian title index, this scenario should not occur in a normal case (even if front articles could be theoritically be something else than HTML). Right?

@kelson42 That's partly right. libzim7 provides facilities for addressing the said problem but doesn't enforce constraints on the front articles. Therefore one can create (via the libzim7 API) a ZIM file with all front entries being non-HTML items.

**Comment by mgautierfr** [comment] 2021-12-07 10:57
> Rename Archive::getRandomEntry() to Archive::getRandomHtmlEntry()

I would rather remove the test on the html mimetype if the zim file contains a specific front articles list.

**Comment by kelson42** [comment] 2021-12-07 11:01
@mgautierfr agree with your last comment, but the test seems still necessary for older indexes and documentation seems necessary as well.

**Comment by mgautierfr** [comment] 2021-12-07 13:21
This is documented at libzim level. And we want to drop the wrapper at libkiwix level.
We may still add the information in the documentation but I don't think we want to do more at libkiwix level.

**Comment by automactic** [comment] 2021-12-07 15:24
> @kelson42 Yes, it is. Archive::getRandomEntry() performs at most 42 attempts - if it doesn't get an item with MIME type of test/html then it fails with an exception.

As an kiwix reader developer, what would you suggest me to tell user when this happens? 

Logically it doesn't make sense for `kiwix::NoEntry` to be raised, because as long as there is >=1 article in the zim file, there should be no problem getting a random page

**Comment by veloman-yunkan** [comment] 2021-12-08 18:37
> > @kelson42 Yes, it is. Archive::getRandomEntry() performs at most 42 attempts - if it doesn't get an item with MIME type of test/html then it fails with an exception.
> 
> As an kiwix reader developer, what would you suggest me to tell user when this happens?
> 
> Logically it doesn't make sense for `kiwix::NoEntry` to be raised, because as long as there is >=1 article in the zim file, there should be no problem getting a random page

@automactic 
I would issue a message like "Failed to pick an article (probably because the ZIM file contains too much junk)" :) But me being me, I think that @kelson42 will not approve such text.

**Comment by automactic** [comment] 2021-12-10 03:45
The error message should be "we cannot find a random function because we suck at what we do" /s

Once again, my opinion is a function to get random article should never fail as long as there are at least one article. Imagine what would you say if `rand` only give you a number some of the time, and raise an exception at other times.

Also how is it not considered a regression when on the same zim file, earlier versions of libkiwix can always get a random article, and newer version cannot?

**Comment by kelson42** [comment] 2021-12-10 04:26
@automactic The problem is not like you describe in your comment:
* random function has no dep to anything, the comparison is not good
* what would you say if our function would return always the same article!
* except if we find a new bug somewhere, this is not a regression. Not sure how it was exactly working earlier, but we were not better at finding a random article. Actually from the principle there is now with libzim7 more chance you get a front article than before
* the reader should be ready anyway to get something different than html, included the exception.

@mgautierfr Please check with the given file why so often we don't find a html article. This is a bit strange, maybe the random function is not seeded properly on ios? and We should get rid of this html filtering or rename the method.

**Comment by mgautierfr** [comment] 2021-12-10 13:20
The released version of libkiwix do not have any filter except not returning the mainpage (https://github.com/kiwix/libkiwix/blob/9.4.1/src/reader.cpp#L199-L220)

What is on master (not released) is to use whatever is on libzim.
Libzim (released) does have a filter on the mimetype.
This filter has been introduce in the early stage of libzim7 development, where we move all entries in the same namespace but without a front article list.
At this time we've lost the ability to do a random in `A` namespace and so we add to filter the entries to return something useful.
We should remove the test and simply do a proper random picking in the `A` namespace (for old zim) or front article list (for new one). For the few zims made in between, we may have non html entry picked but I think they are pretty rare as libzim7 was not released.

**Comment by automactic** [comment] 2021-12-10 14:30
@kelson42 

> random function has no dep to anything, the comparison is not good

Hey, we can argue all day long if xyz is a good comparison. But at the end of the day, it is these kiwix apps that users directly use that matters. We cannot tell user there isn't a random article when there are >=1 articles.

> what would you say if our function would return always the same article!

Imagine you retrieve a ball from a bag of balls with replacement, of course it is possible to retrieve the same ball on consecutive tries. But some thing is wrong if it is always the same ball, unless there are only one ball in the bag.

> except if we find a new bug somewhere, this is not a regression. Not sure how it was exactly working earlier, but we were not better at finding a random article. Actually from the principle there is now with libzim7 more chance you get a front article than before

I consider a random function that always give me something to be categorically better than a random function that sometimes cannot to do its job

> the reader should be ready anyway to get something different than html, included the exception.

Sure I agree with this point and I have already changed the code on my side to handle this

> This is a bit strange, maybe the random function is not seeded properly on ios?

iOS did not change, this happens after I shipped app with a newer set of static libs built from `kiwix-build`

**Comment by automactic** [comment] 2021-12-10 14:43
Here is a demo of how often this can happen on a zim file with small article count. And keep in mind, we used to not have a problem cycle through all these pages on earlier versions of libkiwix / libzim.

https://user-images.githubusercontent.com/8294252/145591557-29028400-713f-4f85-8cbd-c340d18ca588.mp4

**Comment by automactic** [comment] 2021-12-10 16:43
As a comparison, this is how things used to behave on a older version of kiwix before I updated libkiwix. Note: both videos are taken on the same device, same zim file and same iOS version

https://user-images.githubusercontent.com/8294252/145609846-a522d714-83b6-440b-a914-796a49dd49ed.mp4

**Comment by kelson42** [comment] 2021-12-14 10:31
@automactic Fixed in libzim with https://github.com/openzim/libzim/pull/650

**Closed by kelson42** 2021-12-14 10:31 UTC
Labels: bug
