### ISSUE TITLE
(A) Search drop-down [incl 10 suggested article titles] (1) never appears, or (2) appears many seconds later, or (3) appears nearly instantly if you type BACKSPACE — or if you hit ENTER, ERR_CONNECTION_REFUSED is very common (B) SEARCH FAILS when search query is a Greek letter like "pi", "alpha", "beta" ETC

### ISSUE THREAD

**Issue by holta** [kiwix/libkiwix#769] opened 2022-05-10 19:44 UTC
This irritating problem (appears) to affect all schools and everyone using very large ZIM files (on Raspberry Pi's especially?)

Specifically, this severe UX glitch occurs very often with very large ZIM files like https://download.kiwix.org/zim/wikipedia/wikipedia_en_all_maxi_2021-12.zim

What happens is that users browse to type in a search query into the top-right (e.g. of http://box.lan/kiwix/wikipedia_en_all_maxi_2021-12/) but the search drop-down menu very often never appears.

Or the drop-down appears Many Seconds Later &mdash; for no obvious reason (zero CPU load, and many gigabytes of RAM available, even when no others users are using kiwix-serve).

The problem occurs with any version of kiwix-tools (kiwix-serve) from recent years (including the very latest 3.2.0-4).

The problem occurs regardless if the https://internet-in-a-box.org is proxying kiwix-serve or if kiwix-serve if being accessed directly over port 3000.

Very Strange Workarounds:

- Typing BACKSPACE sometimes helps, to force the drop-down to finally appear, e.g. by shortening your search query from "AIDS" to "AID"
- Typing "S" to restore your original search query ("AIDS") often then works, to force the drop-down to finally appear

While very useful, not every teacher and student can handle the above quirky workarounds :/

_Does anybody have any idea what the root cause might be &mdash; for this very common usability glitch?_  Apologies I'm not sure exactly what the pattern is!  But certainly it occurs very consistently and commonly despite the intermittent/random nature of the problem &mdash; this seems to affect all schools using very large ZIM files under these common conditions (on Raspberry Pi servers, no matter how recent or how old, the delay does not seem the be affected very strangely...)

BACKGROUND: This longstanding problem has been ongoing in recent years.  I told schools that faster CPU's, more RAM and newer OS's would probably speed things up, such that this irritating delay (or the drop-down never appearing at all!) might effectively cease to be a problem.

I Was 100% Wrong: this confusing problem remains just as severe today in May 2022, even with massive amounts of RAM, fast SSD's instead of microSD cards, the fastest Raspberry Pi &mdash; and no matter whether using 32-bit or 64-bit Raspberry Pi OS Lite.

SIDE EFFECT: Many/most users end up doing Full-Text Search by accident.  As they don't realize there's any other option &mdash; i.e. users often hit "Enter" after typing in a search query &mdash; as a result of the "10 suggestions" drop-down never having appeared.

**Comment by holta** [comment] 2022-05-11 14:27
> On wikipedia_en_all_maxi_2020-08.zim the title xapian database is 2692521984 bytes so 2.5 GB.

@mgautierfr that's a really great explanation (series of explanations!)

Thank you.

Xapian's entire 2.5 GB doesn't need to be loaded into memory as you say &mdash; but if indeed Xapian requires large subsets of that to be moved across the computer's internal bus(es) that would indeed explain a lot :thinking:

(And on the bright side, the better the pattern is understood, the more schools can try to adapt with such realities.)

> But we would have to use the title sorted listing. So only title starting by searched term. And case-sensitive (except if add another case-insensitive listing in zim files along with listing/titleOrdered https://wiki.openzim.org/wiki/Search_indexes)

Certainly the list of 10 suggested article titles will never be perfect &mdash; however this evolves year-by-year, as we know from things like https://github.com/kiwix/kiwix-tools/issues/513 &mdash; and we will live with that, whatever's decided!

:+1:

**Comment by holta** [comment] 2022-05-12 02:32
@mgautierfr this might be unrelated — but schools perceive this to be very much related:

Would you happen to know why about 30% of full-text searches (on Raspberry Pi, as described above, in essentially every school that uses them) fail completely, with the following message if using Chrome browser:

```
This site can’t be reached

box refused to connect.

Try:

Checking the connection
ERR_CONNECTION_REFUSED
```

Reloading the page a couple times often works, i.e. forcing a 2nd attempt, or a 3rd attempt.

There happens when there is no load on the Raspberry Pi 4 server, which has many GB of RAM available, and no other users during testing which had reconfirmed this.

In any case the failures appear to occur very consistently about 30% of the time — at completely random intervals.

FYI this has been reconfirmed using the unproxied URL for example:

- http://box.lan:3000/kiwix/search?content=wikipedia_en_all_maxi_2021-12&pattern=AIDS

NOTE: during testing it's important to use a new search query (search string, a.k.a. search pattern) every time, to avoid caching of prior search results.

**Comment by kelson42** [comment] 2022-05-12 04:18
I propose to wait the libkiwix 10.2.0 release and test again with it. If it still fail, then we will try to investigate to get a clear reproduction case.

**Comment by mgautierfr** [comment] 2022-05-12 09:05
I don't know why the connection is refused but there is another cause of slow down.

By default, kiwix-serve use only 4 threads to answer requests. If the thread pool is full, connection are accepted by the httpd library but directly put in "wait state" until a thread is freed.
If you start searches with "A", "AI", "AID", "AIDS", you have filled your thread pool and no request can be handle until a search is completed.

I've just tested with several fulltext search (changing the pagination) on a zim file on a usb drive (for long io) and on the 6 requests with only 2 threads available, I've "succeed" to have one 500 error (to investigate)
The 500 error is maybe reported as ERR_CONNECTION_REFUSED by the proxy ?

**Comment by kelson42** [comment] 2022-05-12 10:37
@mgautierfr We should implement https://github.com/kiwix/libkiwix/issues/395 to avoid one thread to be occuped too long and assure a better distribution of threads usage.

**Comment by holta** [comment] 2022-05-12 10:46
Thank you for the explanations & suggestions!

Quick questions below:

> If you start searches with "A", "AI", "AID", "AIDS", you have filled your thread pool and no request can be handle until a search is completed.

Do you know if that applies when the user types in their search string very slowly — does this effectively launch 4 Xapian Title Searches — i.e. using up all 4 threads?

Search strings longer than 4 letters might use up all threads if so, causing serious resource starvation — _if slow typing really does exacerbate these problems ?_

(e.g. Is it important not to pause between each letter while typing in a search string?)

> I propose to wait the libkiwix 10.2.0 release and test again with it.

Good to know.  Roughly when is that (likely) expected?

**Comment by kelson42** [comment] 2022-05-12 10:51
> > I propose to wait the libkiwix 10.2.0 release and test again with it.
> 
> Good to know. Roughly when is that (likely) expected?

I expect within a week.

**Comment by holta** [comment] 2022-05-12 11:27
Just FYI all testing mentioned above was reconfirmed with kiwix-tools 3.2.0-4:

```
root@box:/opt/iiab/kiwix/bin# ./kiwix-serve --version
kiwix-tools 3.2.0

libkiwix 10.1.1
+ libzim 7.2.1
+ libxapian 1.4.18
+ libcurl 7.67.0
+ libmicrohttpd 0.9.72
+ libz 1.2.12
+ libicu 58.2.0
+ libpugixml 0.12.0

libzim 7.2.1
+ libzstd 1.5.2
+ liblzma 5.2.4
+ libxapian 1.4.18
+ libicu 58.2.0
```

**Comment by kelson42** [comment] 2022-06-26 12:51
@holta Would you be able please to provide an update with kiwix-tools 3.3.0?

**Comment by holta** [comment] 2022-06-26 15:47
For the moment I cannot reproduce the search drop-down's severe slowness on Raspberry Pi 4 with these 2 different versions of kiwix-tools &mdash; those were kiwix-tools 3.2.0-1 from 2022-02-02...

```
# kiwix-serve --version

kiwix-tools 3.2.0

libkiwix 10.0.1
+ libzim 7.2.0
+ libxapian 1.4.18
+ libcurl 7.67.0
+ libmicrohttpd 0.9.72
+ libz 1.2.8
+ libicu 58.2.0
+ libpugixml 0.12.0

libzim 7.2.0
+ libzstd 1.5.1
+ liblzma 5.2.4
+ libxapian 1.4.18
+ libicu 58.2.0
```

And kiwix-tools 3.3.0 from 2022-06-15...

```
# kiwix-serve --version

kiwix-tools 3.3.0

libkiwix 11.0.0
+ libzim 7.2.2
+ libxapian 1.4.18
+ libcurl 7.67.0
+ libmicrohttpd 0.9.72
+ libz 1.2.12
+ libicu 58.2.0
+ libpugixml 0.12.0

libzim 7.2.2
+ libzstd 1.5.2
+ liblzma 5.2.4
+ libxapian 1.4.18
+ libicu 58.2.0
```

On the own hand this appears to be good news.  On the other hand, I'd like to understand why I (and others) had so much trouble with kiwix-serve 3.2.0-4 back in early May.  I'll try to do more tests in coming days to see if this can be better understood.

FYI both above tests used http://box/kiwix/wikipedia_en_all_maxi_2021-12/

**Comment by kelson42** [comment] 2022-06-26 15:53
@holta Do you use the same hardware (rpi+sd) as a few months ago?

**Comment by holta** [comment] 2022-06-26 15:56
> @holta Do you use the same hardware (rpi+sd) as a few months ago?

Yes.

Strangely I also cannot reproduce the slowness when using kiwix-tools 3.2.0-4 just as in early May.

But am using a different OS today: for the moment anyway I'm using the 32-bit Raspberry Pi OS on Raspberry Pi 4, whereas in early May I was using the 64-bit version of Raspberry Pi OS on Raspberry Pi 4.

So hypothetically the slowness flaw _might_ be arising from using *armhf* builds of kiwix-tools on 64-bit Raspberry Pi OS??
(I'll investigate more in coming days.)

**Comment by kelson42** [comment] 2022-06-26 16:20
@holta Quite impatient to know more about your investigations :)

**Comment by kelson42** [comment] 2022-10-24 15:03
@holta latest libzim/libkiwix/kiwix-tools are still not released yet, but will have to tackle this in the next months. Do you know at least if this still appear with latest nightly of kiwix-serve?

**Comment by holta** [comment] 2022-10-24 18:54
> quickly typing in the search query "aids" fails to display the search dropdown about 80% of the time

Quick Tests: I can't reproduce the above with kiwix-tools nightly build 2022-10-24, with the latest Raspberry Pi OS:

Search query "AIDS" is slow to appear, but appeared every time within about 5-10 seconds.

> type out Greek letters e.g. "alpha" "beta" "omicron" etc (the letter "mu" is the only exception, among all 24 Greek letters). To be clear: the search drop-down did not appear

The above failure however DOES occur every time — EXAMPLE:
- The search query "pi" will never work (as it's a Greek letter, try it!)
- Adding or removing a letter (e.g. "p" or "pit") will however work.

**Comment by kelson42** [comment] 2022-10-24 19:22
@mgautierfr Might that be that this ticket has been a duplicate of https://github.com/kiwix/kiwix-tools/issues/573? For latest "pi" stuff stringly suspect a stopword on steeming which fails, what donyou think?

**Comment by kelson42** [comment] 2022-11-01 18:38
@mgautierfr A feedback?

**Comment by kelson42** [comment] 2022-11-03 12:35
I had a look to the problem with "pi" and the problem is related to wrong json escaping, see this:
```
$ curl "http://127.0.0.1:8080/suggest?content=wikipedia_en_all_nopic_2022-01&term=pi" | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1317  100  1317    0     0  24687      0 --:--:-- --:--:-- --:--:-- 24849
parse error: Invalid escape at line 27, column 19
```
@veloman-yunkan Would you be able to quickly fit that (and adapt the test)? In general I wonder that we have this kind of bug, we don't use an external primitive to do the json escaping?!

**Comment by kelson42** [comment] 2022-11-09 14:04
@veloman-yunkan Any feedback? this seems to me to be a blocker for `12.0.0` release

**Comment by kelson42** [comment] 2022-11-17 10:49
All should work fine now

**Closed by kelson42** 2022-11-17 10:49 UTC
Labels: bug, enhancement, question, kiwix-serve, search
