### ISSUE TITLE
libkiwix 13.0.0 cancelled / removed

### ISSUE THREAD

**Issue by mgautierfr** [kiwix/libkiwix#1000] opened 2023-09-18 10:08 UTC
This is an issue to advertise that we (I) have published libkiwix 13.0.0 a bit too early and so we are now proceeding with a recall.

Short story :
I have made a release 13.0.0 of libkiwix, and we are now recalling it.
We have not really advertised anythign (no official github release) but we have created tag 13.0.0 and published sources and build of libkiwix (other projects are not impacted).
Now tag 13.0.0 is deleted and the published source and build are renamed with underscore (`_`) postfix.
(Those archives will be deleted once this issue is fixed).

Long story:
We have published `12.1.0` but it has api/abi breaks we didn't detect. So it should have been a new major version (ie `13.0.0`).
Once we have detected that, we have published version `12.1.1` which removes the api break.
At the same time, I have published libkiwix `13.0.0` (which is the same thing than `12.1.0`, but with a different name) to emphasize that we have an api break between 12.0.0 and 13.0.0

After internal discussion with the team, we agreed that this publication was a bit too early as we are planning to release a "real" 13.0.0 really soon.
So we are recalling it. The new 13.0.0 should come before the end of the week.

For any user detecting the release removal, you now know why.
If you have any comments, this is the place to do it.

Ping @legoktm @xvitaly @kiwix/lieutenants

**Comment by kelson42** [comment] 2023-10-08 14:59
Duplicate of #981

**Closed by kelson42** 2023-10-08 14:59 UTC
Labels: task
