### ISSUE TITLE
Search in Chinese fails beyond one character

### ISSUE THREAD

**Issue by Popolechien** [kiwix/libkiwix#1034] opened 2023-12-15 07:35 UTC
(not 100% sure this is the right repo, feel free to move)

A user reported that searching for words in Chinese only works when one character is used: after that, the search box returns no results as in the examples below `电 ` is ok, but `电介` is not (eventhough you see it at the bottom of the first screenshot)
<img src="https://github.com/kiwix/libkiwix/assets/21675885/48d09192-ce59-4d46-92cd-23243358025c" width=250>
<img src="https://github.com/kiwix/libkiwix/assets/21675885/0c319e6e-4221-432d-88e7-18690d50f522" width=250>

**Comment by kelson42** [comment] 2023-12-15 07:37
Duplicate of https://github.com/openzim/libzim/issues/794

**Closed** 2023-12-15 07:37 UTC
Labels: bug, duplicate
