### ISSUE TITLE
Add book titles to search results

### ISSUE THREAD

**Issue by thavelick** [kiwix/libkiwix#704] opened 2022-02-07 02:14 UTC
When seaching across multiple zim archives it would be useful to be able to see which archive each search result came from to avoid confusion. 

For instance, in my case I have Wikipedia, archwiki, and python documentation amongst others set up with kiwix-serve. If I seach for something technical like `Python` across all these books, it can be really confusing which book each result came from.

Most public search engines have a bit of text under each search result that shows what site results come from. By adding the book title at the bottom of each result, we can emulate a behaviour lots of users have come to expect.

One possible downside is that the book titles will clutter the search results, but a few words per search result don't seem to distract too much.

**Comment by kelson42** [comment] 2022-02-07 05:08
Seems to be a duplicate of https://github.com/kiwix/kiwix-tools/issues/478

**Closed** 2022-02-16 11:59 UTC
Labels: enhancement, search
