### ISSUE TITLE
Kiwix-serve random end-point missing under certain condition

### ISSUE THREAD

**Issue by rgaudin** [kiwix/libkiwix#588] opened 2021-07-21 17:16 UTC
Clicking the random dice returns `/random?content=3dprinting_stackexchange_com_2021-07`-like URL which raises the standard libkiwix 404 Error page
 
<img width="440" alt="Screen Shot 2021-07-21 at 17 14 09" src="https://user-images.githubusercontent.com/57929/126531113-250d5787-ec36-4172-ae70-1c8abf0408f9.png">

This is from `2021-07-21` nightly of kiwix-tools and was already present in the nightly from `2021-07-07`.

**Comment by kelson42** [comment] 2021-07-22 05:01
@veloman-yunkan Any clue why this end-point seems to have disappear?

**Comment by veloman-yunkan** [comment] 2021-07-24 10:45
@rgaudin Cannot reproduce this issue. Please provide a test case.

**Comment by rgaudin** [comment] 2021-07-24 13:34
@veloman-yunkan thanks for this reply. I realize now it happens only on new sotoki zim files such as [this one](http://tmp.kiwix.org/beer_stackexchange_com_2021-07__nobase.zim).

Could it be because we lack hints in pylibzim and none of our entries are marked as FRONT_ARTICLE ? Or maybe it's related to https://github.com/openzim/libzim/issues/590 ?

**Comment by kelson42** [comment] 2021-07-24 13:40
@rgaudin Hmmm, similar? Duplicate of https://github.com/openzim/warc2zim/issues/37 ?

**Comment by rgaudin** [comment] 2021-07-24 13:43
Root cause is probably the same but there's definitely a bug here. Either we fallback to elsewhere (mainPath?) or a dedicated error message must be shown.

**Comment by veloman-yunkan** [comment] 2021-07-24 13:56
> Could it be because we lack hints in pylibzim and none of our entries are marked as FRONT_ARTICLE ?

@rgaudin This is a very likely reason - `zim::Archive::getRandomEntry()` picks up an item from the front entry list: https://github.com/openzim/libzim/blob/20c0e3019c97f367acb0ba3c86f9dcd04ca44e77/src/archive.cpp#L255-L272

For ZIM archives created by new libzim the front entry list is stored in `X/listing/titleOrdered/v1` which remains empty. So *not using hints* is probably the actual problem behind openzim/libzim#590.

**Comment by kelson42** [comment] 2021-08-03 10:57
Reassigning to @mgautierfr because he is going to fix the bug (python-)libzim

**Comment by rgaudin** [comment] 2021-08-04 13:36
Agrees with @mgautierfr  and confirms with Hints the random button works as expected.

**Comment by kelson42** [comment] 2021-08-20 13:51
@rgaudin @mgautierfr I would be in favor of closing this. After https://github.com/openzim/libzim/pull/604 this problem should not occur anymore.

**Closed** 2021-08-25 15:24 UTC
Labels: bug, kiwix-serve
