### ISSUE TITLE
Kiwix-serve 3.1.2-5-rc1, memory error on RPi 

### ISSUE THREAD

**Issue by eroyee** [kiwix/libkiwix#551] opened 2021-06-09 22:39 UTC
I was having issues with kiwix-serve becoming unresponsive and holding 1 core of my Pi at ~100% per #513 

I downloaded kiwix-tools_linux-armhf-3.1.2-5-rc1.tar.gz and trialled that version of kiwix-serve.

While the original issue appears resolved I get a memory error after several clicks of the dice and the system becomes unresponsive. When this first occurred it eventually returned to operation without intervention after several minutes. 

A second trial replicated the issue found in the first, however in this instance the landing page worked showing the various sites, but attempting to enter any one of them gives:

_Internal Server Error

An internal server error occured. We are sorry about that :/

Allocation error : not enough memory_ 

This is on a Pi3 with typically < 0.1 load average and reasonable remaining memory.

Zim's loaded are:

_engineering.stackexchange.com_en_all_2021-04.zim
latin.stackexchange.com_en_all_2021-05.zim 
physics.stackexchange.com_en_all_2021-05.zim 
/wiktionary_en_all_maxi_2021-03.zim 
history.stackexchange.com_en_all_2021-04.zim
law.stackexchange.com_en_all_2021-04.zim 
wikipedia_en_all_maxi.zim_

Further info:

~# ./kiwix-serve -d --port=8080 /mnt/usbdisk1/zims/engineering.stackexchange.com_en_all_2021-04.zim /mnt/usbdisk1/zims/latin.stackexchange.com_en_all_2021-05.zim /mnt/usbdisk1/zims/physics.stackexchange.com_en_all_2021-05.zim /mnt/usbdisk1/zims/wiktionary_en_all_maxi_2021-03.zim /mnt/usbdisk1/zims/history.stackexchange.com_en_all_2021-04.zim /mnt/usbdisk1/zims/law.stackexchange.com_en_all_2021-04.zim /mnt/usbdisk1/zims/wikipedia_en_all_maxi.zim
root@raspbx:/home/luke# ./kiwix-serve -d --port=8080 /mnt/usbdisk1/zims/engineering.stackexchange.com_en_all_2021-04.zim /mnt/usbdisk1/zims/latin.stackexchange.com_en_all_2021-05.zim /mnt/usbdisk1/zims/physics.stackexchange.com_en_all_2021-05.zim /mnt/usbdisk1/zims/wiktionary_en_all_maxi_2021-03.zim /mnt/usbdisk1/zims/history.stackexchange.com_en_all_2021-04.zim /mnt/usbdisk1/zims/law.stackexchange.com_en_all_2021-04.zim /mnt/usbdisk1/zims/wikipedia_en_all_maxi.zim

~# ===== Unhandled error : Allocation error : not enough memory
========== INTERNAL ERROR !! ============
Requesting : 
full_url : /wikipedia_en_all_maxi/A/KVAL-TV
method    : GET (0)
version   : HTTP/1.1
request#  : 167
headers   :
 - accept : 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8'
 - accept-encoding : 'gzip, deflate'
 - accept-language : 'en-US,en;q=0.5'
 - connection : 'keep-alive'
 - cookie : 'ys-epggrid=o%3Acolumns%3Da%253Ao%25253Aid%25253Ds%2525253Adetails%25255Ewidth%25253Dn%2525253A67%255Eo%25253Aid%25253Dn%2525253A1%25255Ewidth%25253Dn%2525253A100%255Eo%25253Aid%25253Ds%2525253Atitle%25255Ewidth%25253Dn%2525253A250%255Eo%25253Aid%25253Ds%2525253Asubtitle%25255Ewidth%25253Dn%2525253A250%255Eo%25253Aid%25253Ds%2525253AepisodeOnscreen%25255Ewidth%25253Dn%2525253A100%255Eo%25253Aid%25253Ds%2525253Astart%25255Ewidth%25253Dn%2525253A117%255Eo%25253Aid%25253Ds%2525253Astop%25255Ewidth%25253Dn%2525253A100%25255Ehidden%25253Db%2525253A1%255Eo%25253Aid%25253Ds%2525253Aduration%25255Ewidth%25253Dn%2525253A100%255Eo%25253Aid%25253Ds%2525253AchannelNumber%25255Ewidth%25253Dn%2525253A60%255Eo%25253Aid%25253Ds%2525253AchannelName%25255Ewidth%25253Dn%2525253A250%255Eo%25253Aid%25253Ds%2525253AstarRating%25255Ewidth%25253Dn%2525253A50%255Eo%25253Aid%25253Ds%2525253AageRating%25255Ewidth%25253Dn%2525253A50%255Eo%25253Aid%25253Ds%2525253Agenre%25255Ewidth%25253Dn%2525253A250%5Efilters%3Do%253A'
 - dnt : '1'
 - host : '192.168.1.50:8080'
 - referer : 'http://192.168.1.50:8080/wikipedia_en_all_maxi/A/Orta_%C3%87al%C4%9Fan'
 - upgrade-insecure-requests : '1'
 - user-agent : 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0'
arguments :
Parsed : 
full_url: /wikipedia_en_all_maxi/A/KVAL-TV
url   : /wikipedia_en_all_maxi/A/KVAL-TV
acceptEncodingDeflate : 1
has_range : 0
is_valid_url : 1
.............
Response :
httpResponseCode : 500
headers :
 - Content-Type: 'text/html'
 - Access-Control-Allow-Origin: '*'
 - Cache-Control: 'no-cache, no-store, must-revalidate'
 - Content-Encoding: 'deflate'
 - Vary: 'Accept-Encoding'
===== Unhandled error : Allocation error : not enough memory
========== INTERNAL ERROR !! ============
Requesting : 
full_url : /wikipedia_en_all_maxi/A/Dimensional_analysis
method    : GET (0)
version   : HTTP/1.1
request#  : 169
headers   :
 - accept : 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8'
 - accept-encoding : 'gzip, deflate'
 - accept-language : 'en-US,en;q=0.5'
 - connection : 'keep-alive'
 - cookie : 'ys-epggrid=o%3Acolumns%3Da%253Ao%25253Aid%25253Ds%2525253Adetails%25255Ewidth%25253Dn%2525253A67%255Eo%25253Aid%25253Dn%2525253A1%25255Ewidth%25253Dn%2525253A100%255Eo%25253Aid%25253Ds%2525253Atitle%25255Ewidth%25253Dn%2525253A250%255Eo%25253Aid%25253Ds%2525253Asubtitle%25255Ewidth%25253Dn%2525253A250%255Eo%25253Aid%25253Ds%2525253AepisodeOnscreen%25255Ewidth%25253Dn%2525253A100%255Eo%25253Aid%25253Ds%2525253Astart%25255Ewidth%25253Dn%2525253A117%255Eo%25253Aid%25253Ds%2525253Astop%25255Ewidth%25253Dn%2525253A100%25255Ehidden%25253Db%2525253A1%255Eo%25253Aid%25253Ds%2525253Aduration%25255Ewidth%25253Dn%2525253A100%255Eo%25253Aid%25253Ds%2525253AchannelNumber%25255Ewidth%25253Dn%2525253A60%255Eo%25253Aid%25253Ds%2525253AchannelName%25255Ewidth%25253Dn%2525253A250%255Eo%25253Aid%25253Ds%2525253AstarRating%25255Ewidth%25253Dn%2525253A50%255Eo%25253Aid%25253Ds%2525253AageRating%25255Ewidth%25253Dn%2525253A50%255Eo%25253Aid%25253Ds%2525253Agenre%25255Ewidth%25253Dn%2525253A250%5Efilters%3Do%253A'
 - dnt : '1'
 - host : '192.168.1.50:8080'
 - referer : 'http://192.168.1.50:8080/wikipedia_en_all_maxi/A/Orta_%C3%87al%C4%9Fan'
 - upgrade-insecure-requests : '1'
 - user-agent : 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0'
arguments :
Parsed : 
full_url: /wikipedia_en_all_maxi/A/Dimensional_analysis
url   : /wikipedia_en_all_maxi/A/Dimensional_analysis
acceptEncodingDeflate : 1
has_range : 0
is_valid_url : 1
.............
Response :
httpResponseCode : 500
headers :
 - Content-Type: 'text/html'
 - Access-Control-Allow-Origin: '*'
 - Cache-Control: 'no-cache, no-store, must-revalidate'
 - Content-Encoding: 'deflate'
 - Vary: 'Accept-Encoding'
===== Unhandled error : Allocation error : not enough memory
========== INTERNAL ERROR !! ============
Requesting : 
full_url : /wikipedia_en_all_maxi/A/Məşrif
method    : GET (0)
version   : HTTP/1.1
request#  : 170
headers   :
 - accept : 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8'
 - accept-encoding : 'gzip, deflate'
 - accept-language : 'en-US,en;q=0.5'
 - connection : 'keep-alive'
 - cookie : 'ys-epggrid=o%3Acolumns%3Da%253Ao%25253Aid%25253Ds%2525253Adetails%25255Ewidth%25253Dn%2525253A67%255Eo%25253Aid%25253Dn%2525253A1%25255Ewidth%25253Dn%2525253A100%255Eo%25253Aid%25253Ds%2525253Atitle%25255Ewidth%25253Dn%2525253A250%255Eo%25253Aid%25253Ds%2525253Asubtitle%25255Ewidth%25253Dn%2525253A250%255Eo%25253Aid%25253Ds%2525253AepisodeOnscreen%25255Ewidth%25253Dn%2525253A100%255Eo%25253Aid%25253Ds%2525253Astart%25255Ewidth%25253Dn%2525253A117%255Eo%25253Aid%25253Ds%2525253Astop%25255Ewidth%25253Dn%2525253A100%25255Ehidden%25253Db%2525253A1%255Eo%25253Aid%25253Ds%2525253Aduration%25255Ewidth%25253Dn%2525253A100%255Eo%25253Aid%25253Ds%2525253AchannelNumber%25255Ewidth%25253Dn%2525253A60%255Eo%25253Aid%25253Ds%2525253AchannelName%25255Ewidth%25253Dn%2525253A250%255Eo%25253Aid%25253Ds%2525253AstarRating%25255Ewidth%25253Dn%2525253A50%255Eo%25253Aid%25253Ds%2525253AageRating%25255Ewidth%25253Dn%2525253A50%255Eo%25253Aid%25253Ds%2525253Agenre%25255Ewidth%25253Dn%2525253A250%5Efilters%3Do%253A'
 - dnt : '1'
 - host : '192.168.1.50:8080'
 - referer : 'http://192.168.1.50:8080/wikipedia_en_all_maxi/A/Orta_%C3%87al%C4%9Fan'
 - upgrade-insecure-requests : '1'
 - user-agent : 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0'
arguments :
Parsed : 
full_url: /wikipedia_en_all_maxi/A/Məşrif
url   : /wikipedia_en_all_maxi/A/Məşrif
acceptEncodingDeflate : 1
has_range : 0
is_valid_url : 1
.............
Response :
httpResponseCode : 500
headers :
 - Content-Type: 'text/html'
 - Access-Control-Allow-Origin: '*'
 - Cache-Control: 'no-cache, no-store, must-revalidate'
 - Content-Encoding: 'deflate'
 - Vary: 'Accept-Encoding'
===== Unhandled error : Unexpected lzma status : 5
========== INTERNAL ERROR !! ============
Requesting : 
full_url : /history.stackexchange.com_en_all_2021-04/A/index.html
method    : GET (0)
version   : HTTP/1.1
request#  : 173
headers   :
 - accept : 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8'
 - accept-encoding : 'gzip, deflate'
 - accept-language : 'en-US,en;q=0.5'
 - connection : 'keep-alive'
 - cookie : 'ys-epggrid=o%3Acolumns%3Da%253Ao%25253Aid%25253Ds%2525253Adetails%25255Ewidth%25253Dn%2525253A67%255Eo%25253Aid%25253Dn%2525253A1%25255Ewidth%25253Dn%2525253A100%255Eo%25253Aid%25253Ds%2525253Atitle%25255Ewidth%25253Dn%2525253A250%255Eo%25253Aid%25253Ds%2525253Asubtitle%25255Ewidth%25253Dn%2525253A250%255Eo%25253Aid%25253Ds%2525253AepisodeOnscreen%25255Ewidth%25253Dn%2525253A100%255Eo%25253Aid%25253Ds%2525253Astart%25255Ewidth%25253Dn%2525253A117%255Eo%25253Aid%25253Ds%2525253Astop%25255Ewidth%25253Dn%2525253A100%25255Ehidden%25253Db%2525253A1%255Eo%25253Aid%25253Ds%2525253Aduration%25255Ewidth%25253Dn%2525253A100%255Eo%25253Aid%25253Ds%2525253AchannelNumber%25255Ewidth%25253Dn%2525253A60%255Eo%25253Aid%25253Ds%2525253AchannelName%25255Ewidth%25253Dn%2525253A250%255Eo%25253Aid%25253Ds%2525253AstarRating%25255Ewidth%25253Dn%2525253A50%255Eo%25253Aid%25253Ds%2525253AageRating%25255Ewidth%25253Dn%2525253A50%255Eo%25253Aid%25253Ds%2525253Agenre%25255Ewidth%25253Dn%2525253A250%5Efilters%3Do%253A'
 - dnt : '1'
 - host : '192.168.1.50:8080'
 - referer : 'http://192.168.1.50:8080/'
 - upgrade-insecure-requests : '1'
 - user-agent : 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0'
arguments :
Parsed : 
full_url: /history.stackexchange.com_en_all_2021-04/A/index.html
url   : /history.stackexchange.com_en_all_2021-04/A/index.html
acceptEncodingDeflate : 1
has_range : 0
is_valid_url : 1
.............
Response :
httpResponseCode : 500
headers :
 - Content-Type: 'text/html'
 - Access-Control-Allow-Origin: '*'
 - Cache-Control: 'no-cache, no-store, must-revalidate'
 - Content-Encoding: 'deflate'
 - Vary: 'Accept-Encoding'
===== Unhandled error : Unexpected lzma status : 5
========== INTERNAL ERROR !! ============
Requesting : 
full_url : /history.stackexchange.com_en_all_2021-04/A/index.html
method    : GET (0)
version   : HTTP/1.1
request#  : 174
headers   :
 - accept : 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8'
 - accept-encoding : 'gzip, deflate'
 - accept-language : 'en-US,en;q=0.5'
 - cache-control : 'max-age=0'
 - connection : 'keep-alive'
 - cookie : 'ys-epggrid=o%3Acolumns%3Da%253Ao%25253Aid%25253Ds%2525253Adetails%25255Ewidth%25253Dn%2525253A67%255Eo%25253Aid%25253Dn%2525253A1%25255Ewidth%25253Dn%2525253A100%255Eo%25253Aid%25253Ds%2525253Atitle%25255Ewidth%25253Dn%2525253A250%255Eo%25253Aid%25253Ds%2525253Asubtitle%25255Ewidth%25253Dn%2525253A250%255Eo%25253Aid%25253Ds%2525253AepisodeOnscreen%25255Ewidth%25253Dn%2525253A100%255Eo%25253Aid%25253Ds%2525253Astart%25255Ewidth%25253Dn%2525253A117%255Eo%25253Aid%25253Ds%2525253Astop%25255Ewidth%25253Dn%2525253A100%25255Ehidden%25253Db%2525253A1%255Eo%25253Aid%25253Ds%2525253Aduration%25255Ewidth%25253Dn%2525253A100%255Eo%25253Aid%25253Ds%2525253AchannelNumber%25255Ewidth%25253Dn%2525253A60%255Eo%25253Aid%25253Ds%2525253AchannelName%25255Ewidth%25253Dn%2525253A250%255Eo%25253Aid%25253Ds%2525253AstarRating%25255Ewidth%25253Dn%2525253A50%255Eo%25253Aid%25253Ds%2525253AageRating%25255Ewidth%25253Dn%2525253A50%255Eo%25253Aid%25253Ds%2525253Agenre%25255Ewidth%25253Dn%2525253A250%5Efilters%3Do%253A'
 - dnt : '1'
 - host : '192.168.1.50:8080'
 - referer : 'http://192.168.1.50:8080/'
 - upgrade-insecure-requests : '1'
 - user-agent : 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0'
arguments :
Parsed : 
full_url: /history.stackexchange.com_en_all_2021-04/A/index.html
url   : /history.stackexchange.com_en_all_2021-04/A/index.html
acceptEncodingDeflate : 1
has_range : 0
is_valid_url : 1
.............
Response :
httpResponseCode : 500
headers :
 - Content-Type: 'text/html'
 - Access-Control-Allow-Origin: '*'
 - Cache-Control: 'no-cache, no-store, must-revalidate'
 - Content-Encoding: 'deflate'
 - Vary: 'Accept-Encoding'

**Comment by eroyee** [comment] 2021-06-09 23:35
After a further trial I find myself unable to replicate the issue.

Unfortunately it's not a high-use site and I can only intermittently test it, however I'll leave the note here for a couple of days and if it continues to operate ok will close the ticket.

**Comment by eroyee** [comment] 2021-06-10 00:01
Several more trials and the issue returns.

I've now specified 8 threads as I wanted to see if it helped (answer, maybe slightly :-/) but I seem to be able to reliably replicate the problem if I open up wikipedia, look at some entries (Lewis Carroll say), open further references in other tabs, close them, then click on the dice several times, then up to landing page and into another library or two, then click the dice again a few times.

When it crashes top shows:

KiB Mem :   948304 total,    47652 free,   321248 used,   579404 buff/cache
KiB Swap:   208880 total,    10012 free,   198868 used.   559892 avail Mem 

Kiwix-serve will not recover and I need to kill the process. It starts again without issue.

I should have mentioned before but the OS is:

Description:	Raspbian GNU/Linux 9.13 (stretch)
Release:	9.13
Codename:	stretch

Yes, I realise there is Buster, but this system also runs another service that's a bit complicated to set up (and transfer) so I need to stick with this at present. It is fully updated.

FWIW here's a further example output, much the same as the others:

===== Unhandled error : Allocation error : not enough memory
========== INTERNAL ERROR !! ============
Requesting : 
full_url : /wiktionary_en_all_maxi_2021-03/A/suggest
method    : GET (0)
version   : HTTP/1.1
request#  : 172
headers   :
 - accept : 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8'
 - accept-encoding : 'gzip, deflate'
 - accept-language : 'en-US,en;q=0.5'
 - connection : 'keep-alive'
 - cookie : 'PHPSESSID=992e2g885kfu9u8qa0shum5hq5; ys-epggrid=o%3Acolumns%3Da%253Ao%25253Aid%25253Ds%2525253Adetails%25255Ewidth%25253Dn%2525253A67%255Eo%25253Aid%25253Dn%2525253A1%25255Ewidth%25253Dn%2525253A100%255Eo%25253Aid%25253Ds%2525253Atitle%25255Ewidth%25253Dn%2525253A250%255Eo%25253Aid%25253Ds%2525253Asubtitle%25255Ewidth%25253Dn%2525253A250%255Eo%25253Aid%25253Ds%2525253AepisodeOnscreen%25255Ewidth%25253Dn%2525253A100%255Eo%25253Aid%25253Ds%2525253Astart%25255Ewidth%25253Dn%2525253A123%255Eo%25253Aid%25253Ds%2525253Astop%25255Ewidth%25253Dn%2525253A100%25255Ehidden%25253Db%2525253A1%255Eo%25253Aid%25253Ds%2525253Aduration%25255Ewidth%25253Dn%2525253A100%255Eo%25253Aid%25253Ds%2525253AchannelNumber%25255Ewidth%25253Dn%2525253A60%255Eo%25253Aid%25253Ds%2525253AchannelName%25255Ewidth%25253Dn%2525253A250%255Eo%25253Aid%25253Ds%2525253AstarRating%25255Ewidth%25253Dn%2525253A50%255Eo%25253Aid%25253Ds%2525253AageRating%25255Ewidth%25253Dn%2525253A50%255Eo%25253Aid%25253Ds%2525253Agenre%25255Ewidth%25253Dn%2525253A250%5Efilters%3Do%253A'
 - dnt : '1'
 - host : '192.168.1.50:8080'
 - referer : 'http://192.168.1.50:8080/wiktionary_en_all_maxi_2021-03/A/Wiktionary:Offline'
 - upgrade-insecure-requests : '1'
 - user-agent : 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:82.0) Gecko/20100101 Firefox/82.0'
arguments :
Parsed : 
full_url: /wiktionary_en_all_maxi_2021-03/A/suggest
url   : /wiktionary_en_all_maxi_2021-03/A/suggest
acceptEncodingDeflate : 1
has_range : 0
is_valid_url : 1
.............
Response :
httpResponseCode : 500
headers :
 - Content-Type: 'text/html'
 - Access-Control-Allow-Origin: '*'
 - Cache-Control: 'no-cache, no-store, must-revalidate'
 - Content-Encoding: 'deflate'
 - Vary: 'Accept-Encoding'

**Comment by kelson42** [comment] 2021-06-10 05:16
@eroyee Please confirm the problem is still there with latest 3.2.2-5 released yesterday and latest nightly as well.

**Comment by kelson42** [comment] 2021-06-10 05:18
@mgautierfr This ticket looks like a duplicate of #512 which has been tested and closed... Does that mean we are not able to reproduce that bug?

**Comment by mgautierfr** [comment] 2021-06-10 08:27
This is the same problem. But we cannot really fix it (at least not more than now).

The root issue is that we have created "wrong" zim files which need a 128Mb buffer **per cluster** when we decompress it.
And as we do partial compression, we store the decompression context in cache along with our clusters.
By default, we store 16 cluster in cache per zim.

This huge memory is not really use (so real memory of the machine is not important) but we reserve 128Mb in the address space.
And on 32bits arch, we only have 4Gb available.
So the address space is quickly exhausted and we have not enough memory.

The new release of libzim 6.3.2 tries to solve this different ways :
- First of all, don't create wrong zim anymore.
- Do not go in a infinite loop when we go out of memory but now raise a exception (so a internal server error (500) on the server side).
- On 32 bits, for cluster compressed with zstd, we don't store the cluster in cache. This slower kiwix-serve, but at least we avoid keeping 16x128Mb per zim.

But this is not perfect. We still reserve 128Mb per "reading". And the more the memory address space is fragmented, the more it will be difficult to find a continuous 128Mb range.

What can be done :
- Reduce the number of threads. Less threads means less parallel reading.
- Replace wrongly zim with new one as we create them.
- Recreate zim files with `zimrecreate` using last version of libzim (http://download.openzim.org/release/zim-tools/zim-tools_linux-x86_64-2.1.0-1.tar.gz)

**Comment by eroyee** [comment] 2021-06-10 10:52
@kelson42 I just trialled today's release (3.1.2-5). 

Eventually I got the same error (see below), but it seemed to take longer to occur - although I can't be definite about that as I've only had time to do limited testing. It's late now but I'm happy to trial further tomorrow night if that's of use?

However from @mgautierfr comment (a good explanation BTW, thanks) there may not be much point in more testing on the current setup?

I've not used zimrecreate before but am happy to try that on the .zim files I have and test again - except it didn't appear to be in the zim-tools_linux-x86_64-2.1.0-1.tar.gz archive. Am I missing something, or just don't understand what I need to do?


===== Unhandled error : Allocation error : not enough memory
========== INTERNAL ERROR !! ============
Requesting : 
full_url : /wikipedia_en_all_maxi/A/Westminster_Abbey
method    : GET (0)
version   : HTTP/1.1
request#  : 25
headers   :
 - accept : 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8'
 - accept-encoding : 'gzip, deflate'
 - accept-language : 'en-US,en;q=0.5'
 - connection : 'keep-alive'
 - cookie : 'PHPSESSID=992e2g885kfu9u8qa0shum5hq5; ys-epggrid=o%3Acolumns%3Da%253Ao%25253Aid%25253Ds%2525253Adetails%25255Ewidth%25253Dn%2525253A67%255Eo%25253Aid%25253Dn%2525253A1%25255Ewidth%25253Dn%2525253A100%255Eo%25253Aid%25253Ds%2525253Atitle%25255Ewidth%25253Dn%2525253A250%255Eo%25253Aid%25253Ds%2525253Asubtitle%25255Ewidth%25253Dn%2525253A250%255Eo%25253Aid%25253Ds%2525253AepisodeOnscreen%25255Ewidth%25253Dn%2525253A100%255Eo%25253Aid%25253Ds%2525253Astart%25255Ewidth%25253Dn%2525253A123%255Eo%25253Aid%25253Ds%2525253Astop%25255Ewidth%25253Dn%2525253A100%25255Ehidden%25253Db%2525253A1%255Eo%25253Aid%25253Ds%2525253Aduration%25255Ewidth%25253Dn%2525253A100%255Eo%25253Aid%25253Ds%2525253AchannelNumber%25255Ewidth%25253Dn%2525253A60%255Eo%25253Aid%25253Ds%2525253AchannelName%25255Ewidth%25253Dn%2525253A250%255Eo%25253Aid%25253Ds%2525253AstarRating%25255Ewidth%25253Dn%2525253A50%255Eo%25253Aid%25253Ds%2525253AageRating%25255Ewidth%25253Dn%2525253A50%255Eo%25253Aid%25253Ds%2525253Agenre%25255Ewidth%25253Dn%2525253A250%5Efilters%3Do%253A'
 - dnt : '1'
 - host : '192.168.1.50:8080'
 - referer : 'http://192.168.1.50:8080/wikipedia_en_all_maxi/A/Lewis_Carroll'
 - upgrade-insecure-requests : '1'
 - user-agent : 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:82.0) Gecko/20100101 Firefox/82.0'
arguments :
Parsed : 
full_url: /wikipedia_en_all_maxi/A/Westminster_Abbey
url   : /wikipedia_en_all_maxi/A/Westminster_Abbey
acceptEncodingDeflate : 1
has_range : 0
is_valid_url : 1
.............
Response :
httpResponseCode : 500
headers :
 - Content-Type: 'text/html'
 - Access-Control-Allow-Origin: '*'
 - Cache-Control: 'no-cache, no-store, must-revalidate'
 - Content-Encoding: 'deflate'
 - Vary: 'Accept-Encoding'
===== Unhandled error : Allocation error : not enough memory
========== INTERNAL ERROR !! ============
Requesting : 
full_url : /wikipedia_en_all_maxi/A/Abdelkader_Harizi
method    : GET (0)
version   : HTTP/1.1
request#  : 640
headers   :
 - accept : 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8'
 - accept-encoding : 'gzip, deflate'
 - accept-language : 'en-US,en;q=0.5'
 - connection : 'keep-alive'
 - cookie : 'PHPSESSID=992e2g885kfu9u8qa0shum5hq5; ys-epggrid=o%3Acolumns%3Da%253Ao%25253Aid%25253Ds%2525253Adetails%25255Ewidth%25253Dn%2525253A67%255Eo%25253Aid%25253Dn%2525253A1%25255Ewidth%25253Dn%2525253A100%255Eo%25253Aid%25253Ds%2525253Atitle%25255Ewidth%25253Dn%2525253A250%255Eo%25253Aid%25253Ds%2525253Asubtitle%25255Ewidth%25253Dn%2525253A250%255Eo%25253Aid%25253Ds%2525253AepisodeOnscreen%25255Ewidth%25253Dn%2525253A100%255Eo%25253Aid%25253Ds%2525253Astart%25255Ewidth%25253Dn%2525253A123%255Eo%25253Aid%25253Ds%2525253Astop%25255Ewidth%25253Dn%2525253A100%25255Ehidden%25253Db%2525253A1%255Eo%25253Aid%25253Ds%2525253Aduration%25255Ewidth%25253Dn%2525253A100%255Eo%25253Aid%25253Ds%2525253AchannelNumber%25255Ewidth%25253Dn%2525253A60%255Eo%25253Aid%25253Ds%2525253AchannelName%25255Ewidth%25253Dn%2525253A250%255Eo%25253Aid%25253Ds%2525253AstarRating%25255Ewidth%25253Dn%2525253A50%255Eo%25253Aid%25253Ds%2525253AageRating%25255Ewidth%25253Dn%2525253A50%255Eo%25253Aid%25253Ds%2525253Agenre%25255Ewidth%25253Dn%2525253A250%5Efilters%3Do%253A'
 - dnt : '1'
 - host : '192.168.1.50:8080'
 - referer : 'http://192.168.1.50:8080/wikipedia_en_all_maxi/A/Government_of_the_Independent_State_of_Croatia'
 - upgrade-insecure-requests : '1'
 - user-agent : 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:82.0) Gecko/20100101 Firefox/82.0'
arguments :
Parsed : 
full_url: /wikipedia_en_all_maxi/A/Abdelkader_Harizi
url   : /wikipedia_en_all_maxi/A/Abdelkader_Harizi
acceptEncodingDeflate : 1
has_range : 0
is_valid_url : 1
.............
Response :
httpResponseCode : 500
headers :
 - Content-Type: 'text/html'
 - Access-Control-Allow-Origin: '*'
 - Cache-Control: 'no-cache, no-store, must-revalidate'
 - Content-Encoding: 'deflate'
 - Vary: 'Accept-Encoding'

**Comment by mgautierfr** [comment] 2021-06-10 12:46
> Am I missing something, or just don't understand what I need to do?

The release process was buggy, I've just published a new archive : http://download.openzim.org/release/zim-tools/zim-tools_linux-x86_64-2.1.0-2.tar.gz

**Comment by kelson42** [comment] 2021-06-10 17:54
Considering that there is nothing more we can do, i will close this ticket.

**Closed by kelson42** 2021-06-10 17:54 UTC
Labels: bug, question

**Comment by eroyee** [comment] 2021-06-12 07:16
@kelson @mgautierfr

I converted four 'old' .zim files using zimrecreate (without option) and 
trialled them. These were:

engineering.stackexchange 553.7MB
physics.stackexchange 3.6GB
wiktionary_en_all_maxi 6.1GB
latin.stackexchange 80.6MB

The PC is still chewing away with wikipedia_en_all_maxi, at this rate 
it'll be a few days.

In my previous tests I'd first used wikipedia, then random other libraries.

In this test I first used physics, then others.

I was not intially able to reproduce the error, however when I did a TLD 
search across the four files (for 'coriolis' :-), then another for 
something else, the server failed.

Here's a representative failure output:

===== Unhandled error : Unexpected lzma status : 5
========== INTERNAL ERROR !! ============
Requesting :
full_url : 
/engineering.stackexchange.com_en_all_2021-04a/A/question/33737.html
method    : GET (0)
version   : HTTP/1.1
request#  : 367
headers   :
  - accept : 
'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8'
  - accept-encoding : 'gzip, deflate'
  - accept-language : 'en-US,en;q=0.5'
  - connection : 'keep-alive'
  - cookie : 
'ys-epggrid=o%3Acolumns%3Da%253Ao%25253Aid%25253Ds%2525253Adetails%25255Ewidth%25253Dn%2525253A67%255Eo%25253Aid%25253Dn%2525253A1%25255Ewidth%25253Dn%2525253A100%255Eo%25253Aid%25253Ds%2525253Atitle%25255Ewidth%25253Dn%2525253A250%255Eo%25253Aid%25253Ds%2525253Asubtitle%25255Ewidth%25253Dn%2525253A250%255Eo%25253Aid%25253Ds%2525253AepisodeOnscreen%25255Ewidth%25253Dn%2525253A100%255Eo%25253Aid%25253Ds%2525253Astart%25255Ewidth%25253Dn%2525253A117%255Eo%25253Aid%25253Ds%2525253Astop%25255Ewidth%25253Dn%2525253A100%25255Ehidden%25253Db%2525253A1%255Eo%25253Aid%25253Ds%2525253Aduration%25255Ewidth%25253Dn%2525253A100%255Eo%25253Aid%25253Ds%2525253AchannelNumber%25255Ewidth%25253Dn%2525253A60%255Eo%25253Aid%25253Ds%2525253AchannelName%25255Ewidth%25253Dn%2525253A250%255Eo%25253Aid%25253Ds%2525253AstarRating%25255Ewidth%25253Dn%2525253A50%255Eo%25253Aid%25253Ds%2525253AageRating%25255Ewidth%25253Dn%2525253A50%255Eo%25253Aid%25253Ds%2525253Agenre%25255Ewidth%25253Dn%2525253A250%5Efilters%3Do%253A'
  - dnt : '1'
  - host : '192.168.1.50:8080'
  - referer : 
'http://192.168.1.50:8080/engineering.stackexchange.com_en_all_2021-04a/A/index.html'
  - upgrade-insecure-requests : '1'
  - user-agent : 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:87.0) 
Gecko/20100101 Firefox/87.0'
arguments :
Parsed :
full_url: 
/engineering.stackexchange.com_en_all_2021-04a/A/question/33737.html
url   : /engineering.stackexchange.com_en_all_2021-04a/A/question/33737.html
acceptEncodingDeflate : 1
has_range : 0
is_valid_url : 1
.............
Response :
httpResponseCode : 500
headers :
  - Content-Type: 'text/html'
  - Access-Control-Allow-Origin: '*'
  - Cache-Control: 'no-cache, no-store, must-revalidate'
  - Content-Encoding: 'deflate'
  - Vary: 'Accept-Encoding'
===== Unhandled error : Unexpected lzma status : 5
===== Unhandled error : Broken promise
===== Unhandled error : Unexpected lzma status : 5


I'm not sure if this information is useful to you, or if you want me to 
do any other tests?

**Comment by kelson42** [comment] 2021-06-12 07:25
@eroyee Can yuou pleade create an other ticket for that please?

**Comment by eroyee** [comment] 2021-06-12 08:46
Done, see #554
