### ISSUE TITLE
jQuery error logs on suggestion hover

### ISSUE THREAD

**Issue by rgaudin** [kiwix/libkiwix#610] opened 2021-08-27 12:26 UTC
Using latest nightly, when using the search bar, I can type in and get a list of suggestions.

When I hover over any of them, I get `Uncaught TypeError: jQuery is undefined` errors in the console (triggered in jquery-ui).

<img width="805" alt="Screen Shot 2021-08-27 at 12 26 27" src="https://user-images.githubusercontent.com/57929/131127152-29c01de9-b73f-4fc2-83c7-ff70d10be843.png">

I can select/click and I am redirected properly to the suggestion though.

**Comment by MananJethwani** [comment] 2021-08-28 15:24
@kelson42 the problem is not related to kiwix-serve but somehow to mwoffliner or more specifically zim-files that have jquery provided with them, they somehow interfere with the jquery we have. looking more into it.

**Comment by rgaudin** [comment] 2021-08-28 15:37
#394 😀

**Comment by rgaudin** [comment] 2021-08-28 15:38
Actually, I think it's an incorrect assumption as the wikiHow I tested it on has zero JS.

**Comment by kelson42** [comment] 2021-08-28 16:08
@MananJethwani The problem of conflicting JS has been fixed in the past, I don't remember the ticket/PR, but this is only a few months ago. I believe like @rgaudin, there is a misinterpretation here.

**Comment by MananJethwani** [comment] 2021-09-01 12:39
@kelson42, the `jquery.noconflict` line in taskbar.js doesn't works properly it changes name to jq, but jqueryUI.min.js tries to look for jquery instead of jq and throws an error.

**Closed** 2022-08-01 13:15 UTC
Labels: bug, kiwix-serve
