### ISSUE TITLE
Add selector for zim tags

### ISSUE THREAD

**Issue by Popolechien** [kiwix/libkiwix#987] opened 2023-08-07 12:42 UTC
Currently the library only lists tags if it is being asked to filter by them:
![Capture d’écran 2023-08-07 à 14 40 31](https://github.com/kiwix/libkiwix/assets/21675885/eb7b9fa9-d7d7-4798-a44b-9db9cb7b2eff)
But with a catalog of several thousand zim files, users would be better served by knowing in advance which kind of tags are available to select, much like categories are already available via a selector.

**Comment by kelson42** [comment] 2023-08-07 15:28
@Popolechien This already has been requested twice and at least for sure once by you. I guess you have all the answers you need there... or not?

**Comment by kelson42** [comment] 2023-09-09 16:00
Duplicate of #582

**Closed by kelson42** 2023-09-09 16:00 UTC
Labels: enhancement, question, good first issue
